### PR TITLE
Fixed custom views getters not generated

### PR DESCRIPTION
**Pull request by maannajjar**
Here's the pull request

### CODE REVIEW

**Comment by tobykurien** [comment]
Thanks!

**Comment by tobykurien** [comment]
I tested this against my project and it now correctly generates getters/setters for custom views. Thanks!

**Comment by maannajjar** [comment]
Great, glad it worked :) You're welcome!

**Comment by Buggaboo** [comment]
Woohoo! *Runs around giving high fives*

**Pull request merged**
